// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_fbTgCEIrkmgB4hVlpgSeh7_f3G2SKxY',
    appId: '1:272383080122:android:4f341c38da8235de71b483',
    messagingSenderId: '272383080122',
    projectId: 'taskgen-ai',
    storageBucket: 'taskgen-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuQ7Ns8k-u9oWPEKbXNdo41TOhcSNB0U',
    appId: '1:272383080122:ios:d4edc8c9c222036771b483',
    messagingSenderId: '272383080122',
    projectId: 'taskgen-ai',
    storageBucket: 'taskgen-ai.appspot.com',
    androidClientId: '272383080122-ab2gegs0dreocvga9dig7638mea3u03v.apps.googleusercontent.com',
    iosClientId: '272383080122-9a5ecd3niopkuep0ba1tbbqb253066bp.apps.googleusercontent.com',
    iosBundleId: 'com.mk.bandu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI6z17l8_EkxYY6eIqSMs-a1bo0OANpw8',
    appId: '1:272383080122:web:b44b01ab2927861671b483',
    messagingSenderId: '272383080122',
    projectId: 'taskgen-ai',
    authDomain: 'taskgen-ai.firebaseapp.com',
    storageBucket: 'taskgen-ai.appspot.com',
    measurementId: 'G-E33WP43702',
  );

}